export const APP_NAME = 'Zenith';
export const APP_NAME_CAPS = APP_NAME.toUpperCase();
export const APP_DESCRIPTION_SHORT = 'A decentralized advertising platform.';
export const APP_HOST= 'https://zenith-six.vercel.app';
export const CURRENCY_SYMBOL = '∾';
export const CURRENCY_NAME = 'MATIC';
export const CHAIN_ID = '0x13881'; // Polygon Mumbai
export const CHAIN_NAME = 'maticmum';
export const TRUFLATION_COUNTRIES = ['us','uk'];
